#!/usr/bin/env node
// cloudflare/build.mjs — assemble ./dist (the static tree the Worker serves) and the generated modules.
//
//   node cloudflare/build.mjs          (from the repository root, or `npm run cf:build` in cloudflare/)
//
// dist/ mirrors the URL space server/index.js serves out of the repository:
//
//   public/**     → dist/**            (/index.html, /js/…, /css/…, /vendor/…, /assets/…, /fonts/…)
//   data/**       → dist/data/**       (/data/config.json …)
//   shared/**     → dist/shared/**     (/shared/protocol.js …)
//   server/sim/** → dist/sim/**        (ES modules only; the Node-only loader nodeData.js is left out)
//   /data.js      → dist/data.js       (the browser stand-in server/index.js generates: DATA_SHIM_JS)
//
// plus two generated modules the Worker imports:
//
//   src/data-modules.generated.js  every data/*.json as text (wrangler Text rule) — see src/data-boot.js
//   src/build-info.generated.js    the browser-runtime build tag /healthz reports (server/index.js buildTag)
//
// Nothing in the repository is modified: dist/ and the two generated files are build products.

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const dist = join(here, 'dist');
const log = (...a) => console.log('[cf-build]', ...a);

/** server/index.js BUILD_INPUTS: the browser runtime the build tag describes. Upstream 0.2.2 added the served
 *  sim/shared/data trees to it — the browser imports /sim/ and /shared/ and caches /data/ JSON, so without them a
 *  simulation-only or data-only deploy would not reach pages that are already open (the page compares this tag
 *  across two /healthz polls and reloads when it changes). */
const BUILD_INPUTS = ['public/index.html', 'public/js', 'public/css', 'server/sim', 'shared', 'data'];
/** server/index.js SIM_PRIVATE: never served (case-insensitive). */
const SIM_PRIVATE = new Set(['nodedata.js']);
/** public/ subdirectories served with a 1-day Cache-Control (server/index.js LONG_CACHE_DIRS). */
const LONG_CACHE_DIRS = ['assets', 'fonts', 'vendor'];
/** Cloudflare's Workers static-asset limits (files per version, bytes per file). */
const MAX_FILES_FREE = 20000;
const MAX_FILES_PAID = 100000;
const MAX_FILE_BYTES = 25 * 1024 * 1024;

// ------------------------------------------------------------------------------------------------
// 1. Sources that must exist first
// ------------------------------------------------------------------------------------------------

if (!existsSync(join(repo, 'public', 'index.html'))) throw new Error(`not a Stronghold-Protocol checkout: ${repo}`);
if (!existsSync(join(repo, 'node_modules'))) throw new Error('run `npm ci` in the repository root first (the build reads server/index.js, which imports ws)');
if (!existsSync(join(repo, 'public', 'vendor'))) {
  log('public/vendor is missing — running tools/vendor.mjs (copies the client libraries from node_modules)');
  const r = spawnSync(process.execPath, [join(repo, 'tools', 'vendor.mjs')], { cwd: repo, stdio: 'inherit' });
  if (r.status !== 0) throw new Error('tools/vendor.mjs failed');
}

// server/index.js is imported for the /data.js stand-in it exports. On forks that add Node-only features to their
// HTTP layer this import can pull in modules the adapter does not need (redis clients, worker pools …) — if it
// fails, fall back to the same stand-in text (it is a five-line module the sim's content imports).
let DATA_SHIM_JS;
try {
  ({ DATA_SHIM_JS } = await import(pathToFileURL(join(repo, 'server', 'index.js')).href));
} catch (e) {
  DATA_SHIM_JS = [
    '// Generated by cloudflare/build.mjs — the browser stand-in for server/data.js (server/http/static.js exports',
    '// the same text; this fallback is used when importing server/index.js fails, e.g. on a fork whose HTTP layer',
    '// pulls in Node-only modules).',
    "import { getSimData } from './sim/simdata.js';",
    'export function getData() { return getSimData() || {}; }',
    'export function resetData() {}',
    '',
  ].join(String.fromCharCode(10));
  log(`WARNING: server/index.js could not be imported (${e && e.message}); using the built-in /data.js stand-in`);
}

// ------------------------------------------------------------------------------------------------
// 2. dist/ — the static tree
// ------------------------------------------------------------------------------------------------

rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

cpSync(join(repo, 'public'), dist, { recursive: true });
cpSync(join(repo, 'data'), join(dist, 'data'), { recursive: true });
cpSync(join(repo, 'shared'), join(dist, 'shared'), { recursive: true });
copySim(join(repo, 'server', 'sim'), join(dist, 'sim'));

writeFileSync(join(dist, 'data.js'), DATA_SHIM_JS);

// The adapter's own client-side additions (never the repository's): the announcement banner and the resource
// preload page. `sp-announce.js` is injected into dist/index.html below — the only change to the served page.
cpSync(join(here, 'public'), dist, { recursive: true });
// A fork that already ships its own announcement client (public/js/ui/announcement.js, e.g. xinhai-ai) renders the
// notices itself and polls the same /api/announcement endpoints — injecting a second banner would double it up.
const upstreamAnnounceClient = existsSync(join(repo, 'public', 'js', 'ui', 'announcement.js'));
if (upstreamAnnounceClient) log('upstream already has an announcement client (public/js/ui/announcement.js) — not injecting /sp-announce.js');
// Does the checkout ship a 「关于本服务器」 dialog? xinhai-ai's fork does (its rows name the fork author); the
// original sganggs 0.2.1 has none. src/public/sp-tweaks.js patches the former and builds its own for the latter —
// which one it is has to be known at build time, so it travels on the script tag.
const checkoutHasAbout = (() => {
  const roots = [join(repo, 'public', 'js'), join(repo, 'shared')];
  const files = [];
  const walk = (dir, depth = 0) => {
    if (depth > 4) return;
    let entries = [];
    try { entries = readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const d of entries) {
      const abs = join(dir, d.name);
      if (d.isDirectory()) walk(abs, depth + 1);
      else if (d.isFile() && d.name.endsWith('.js')) files.push(abs);
    }
  };
  for (const root of roots) walk(root);
  return files.some((file) => {
    try { return /关于本服务器/.test(readFileSync(file, 'utf8')); } catch { return false; }
  });
})();
log(`关于本服务器: the checkout ${checkoutHasAbout ? 'ships its own dialog — sp-tweaks patches it' : 'has none — sp-tweaks provides one when a document is configured'}`);
{
  const indexPath = join(dist, 'index.html');
  let html = readFileSync(indexPath, 'utf8');
  const injected = [];
  // /sp-preload-link.js (the resource-preload chip) is injected on every upstream — it is the entry to /preload
  // on a landing page that has no room for a new button. /sp-announce.js only when the checkout has no
  // announcement client of its own (see above).
  const wanted = [
    ['/sp-preload-link.js', true, ''],
    ['/sp-announce.js', !upstreamAnnounceClient, ''],
    ['/sp-tweaks.js', true, ` data-about-ui="${checkoutHasAbout ? 'checkout' : 'none'}"`],
  ];
  for (const [src, want, extra] of wanted) {
    if (!want || html.includes(src)) continue;
    const tag = `<script src="${src}" defer${extra}></script>`;
    const at = html.lastIndexOf('</body>');
    html = at >= 0 ? `${html.slice(0, at)}  ${tag}\n${html.slice(at)}` : `${html}\n${tag}\n`;
    injected.push(src);
  }
  if (injected.length) {
    writeFileSync(indexPath, html);
    log(`injected ${injected.join(' + ')} into dist/index.html (the repo index.html stays untouched)`);
  }
}

// Content packs (0.2.x, docs/PACKS.md): the pack folders are served under /packs/<id>/<file>, but only the
// files their manifest names (server/packs.js servable) and only through the Worker — see §4 and src/worker.js.
// packs/index.json is deliberately not copied: the server answers it from the live registry, and so does the
// Worker (from src/packs.generated.js).
const packsDir = join(repo, 'packs');
if (existsSync(packsDir)) {
  for (const entry of readdirSync(packsDir, { withFileTypes: true })) {
    if (entry.name === 'index.json') continue; // served dynamically
    cpSync(join(packsDir, entry.name), join(dist, 'packs', entry.name), { recursive: true });
  }
}

// server/index.js answers /data/local-assets.json with an empty manifest when the file is absent (DESIGN §13)
const localArt = join(dist, 'data', 'local-assets.json');
const localArtGroups = existsSync(localArt);
if (!localArtGroups) writeFileSync(localArt, JSON.stringify({ version: 1, source: 'none', count: 0, groups: {} }));

// Cache policy of server/index.js cacheControlFor: html/code/JSON revalidate, /assets|/fonts|/vendor 1 day.
// Everything else keeps the platform default (`public, max-age=0, must-revalidate`) — the same effect.
writeFileSync(join(dist, '_headers'), [
  '# mirrors server/index.js cacheControlFor (LONG_CACHE_DIRS = assets, fonts, vendor)',
  ...LONG_CACHE_DIRS.flatMap((dirName) => [`/${dirName}/*`, '  Cache-Control: public, max-age=86400', '']),
].join('\n'));

// ------------------------------------------------------------------------------------------------
// 2b. dist/data/preload-manifest.json — the resource list for the /preload page
// ------------------------------------------------------------------------------------------------
//
// The preload page (public/preload.js) walks this file: every URL the client will ask for, with the size and
// SHA-256 of the bytes this deployment actually serves. That makes "skip what is already cached" (an
// only-if-cached probe) and "verify what is cached" (length + hash) possible without the page having to know
// how the client derives asset URLs. Entries the game's own manifest names but the server does not have are
// listed separately, so the page can point at `node tools/setup.mjs` instead of just failing.

{
  const { createHash } = await import('node:crypto');
  const wanted = new Set();
  const collect = (node) => {
    if (Array.isArray(node)) { for (const v of node) collect(v); return; }
    if (node && typeof node === 'object') { for (const v of Object.values(node)) collect(v); return; }
    if (typeof node !== 'string') return;
    const p = node.trim();
    if (/^\/(?!\/)/.test(p) && /\.(png|jpe?g|webp|gif|svg|mp3|m4a|aac|ogg|oga|opus|wav|json|skel|atlas|otf|ttf|woff2?)$/i.test(p)) wanted.add(p);
  };
  const readJson = (rel) => { try { return JSON.parse(readFileSync(join(repo, rel), 'utf8')); } catch { return null; } };
  collect(readJson('data/assets.json'));          // every path the game's asset manifest names
  collect(readJson('data/local-assets.json'));    // the optional local-client art (3D board textures …)
  for (const d of readdirSync(join(dist, 'data'))) if (d.endsWith('.json')) wanted.add(`/data/${d}`);
  for (const dir of [join(dist, 'data', 'i18n'), join(dist, 'i18n')]) {
    if (!existsSync(dir)) continue;
    const prefix = dir.startsWith(join(dist, 'data')) ? '/data/i18n/' : '/i18n/';
    for (const f of readdirSync(dir)) if (f.endsWith('.json')) wanted.add(prefix + f);
  }

  const files = [];
  const missing = [];
  let bytes = 0;
  for (const url of [...wanted].sort()) {
    const abs = join(dist, decodeURIComponent(url.slice(1)));
    let st;
    try { st = statSync(abs); } catch { missing.push(url); continue; }
    if (!st.isFile()) { missing.push(url); continue; }
    const hash = createHash('sha256').update(readFileSync(abs)).digest('hex');
    files.push([url, st.size, hash]);
    bytes += st.size;
  }
  writeFileSync(join(dist, 'data', 'preload-manifest.json'), JSON.stringify({
    version: 1,
    app: (() => { try { return /APP_VERSION = '([^']+)'/.exec(readFileSync(join(repo, 'shared', 'constants.js'), 'utf8'))?.[1] ?? null; } catch { return null; } })(),
    generated: new Date().toISOString(),
    files,
    missing,
  }));
  const mib = (n) => (n / 1048576).toFixed(1);
  log(`preload manifest: ${files.length} files, ${mib(bytes)} MiB${missing.length ? `, ${missing.length} missing on the server (run tools/setup.mjs)` : ''}`);
  if (missing.length) log(`       missing examples: ${missing.slice(0, 3).join(', ')}`);
}

// ------------------------------------------------------------------------------------------------
// 3. .generated/ — the server tree the Worker bundles, with the bundler adaptations
// ------------------------------------------------------------------------------------------------
//
// The simulation loads its content modules through *guarded dynamic imports*, so that a broken part is
// logged and skipped instead of taking the server down:
//
//     async function safeImport(path) { try { return await import(path); } catch (e) { …; return {}; } }
//     const DOMAINS = await Promise.all(DOMAIN_NAMES.map((n) => safeImport(`./${n}.js`)));
//     // server/sim/content/kits/index.js: one file per operator kit
//     async function loadKitFile(file) { try { return await import(`./ops/${file}`); } catch { return {}; } }
//     const MODULES = await Promise.all(KIT_FILES.map((group) => Promise.all(group.map(loadKitFile))));
//     // server/sim/content/bonds.js + bands.js: the same shape with literal arguments
//     const [core, addon] = await Promise.all([load('./bonds/core.js'), load('./bonds/addon.js')]);
//
// A bundler resolves `import('…')` only when the specifier is a *literal at the import expression itself*.
// Passing the string into a helper hides it, and the template forms cannot be resolved at all: in the Worker
// those imports would fail at runtime ("No such module devices.js"), silently leaving MODULES/KITS empty —
// no server-side battle simulation (AI teammates, bot rehearsals) and no prep-side effect metas.
//
// So the build copies server/ and shared/ into .generated/ and adapts exactly that pattern:
//   1. the computed imports in server/sim/content/index.js (domain modules) and in
//      server/sim/content/kits/index.js (one kit file per entry of KIT_FILES / STANDIN_KIT_FILES /
//      OPERATOR_KIT_FILES) become literal lists — the names are read back out of the source itself, so a new
//      content module or kit file upstream is picked up automatically;
//   2. every guarded-import helper gains an optional `loading` argument and its literal call sites pass
//      `import('./x.js')` at the call site, where the bundler can see it. The try/catch semantics of the
//      original stay identical — including "a failing part is logged and replaced by {}";
//   3. the result is scanned for any remaining computed dynamic import, and the build fails if one is left.
//
// Everything else in the copy is byte-identical to the repository.

const generated = join(here, '.generated');
rmSync(generated, { recursive: true, force: true });
cpSync(join(repo, 'server'), join(generated, 'server'), { recursive: true });
cpSync(join(repo, 'shared'), join(generated, 'shared'), { recursive: true });
patchContentIndex(join(generated, 'server', 'sim', 'content', 'index.js'));
patchKitsIndex(join(generated, 'server', 'sim', 'content', 'kits', 'index.js'));
adaptGeneratedTree(generated);

/** The content index: computed dynamic imports → literal lists (see §3 note 1). */
function patchContentIndex(file) {
  const src = readFileSync(file, 'utf8');
  // A variant that already passes a literal loader (`safeImport('./tokens.js', () => import('./tokens.js'))` — the
  // shape xinhai-ai's fork uses in its source) needs no rewrite at all: the bundler resolves those by itself.
  if (!/const DOMAINS = await Promise\.all\(DOMAIN_NAMES\.map\(\([^)]*\) => safeImport\(`\.\/\$\{[^}]+\}\.js`\)\)\);/.test(src)) {
    log('.generated/: content modules already use literal loaders — no rewrite needed');
    return;
  }
  const domainsLine = /const DOMAINS = await Promise\.all\(DOMAIN_NAMES\.map\(\(n\) => safeImport\(`\.\/\$\{n\}\.js`\)\)\);/;
  const namesLine = /const DOMAIN_NAMES = \[([^\]]*)\];/;
  const domains = domainsLine.exec(src);
  const names = namesLine.exec(src);
  if (!domains || !names) {
    throw new Error(
      'server/sim/content/index.js no longer matches the expected dynamic-import shape — ' +
      'cloudflare/build.mjs needs the literal rewrite updated (see build.mjs §3)',
    );
  }
  const domainNames = names[1].split(',').map((s) => s.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean);
  if (!domainNames.length) throw new Error('could not read the content module names');
  // (up to 0.1.3 the hand-authored kits were loaded here too, via `./kits/tier${t}.js`; 0.2.x moved that into
  //  content/kits/index.js, handled below — the older line is therefore optional, not required.)
  const tiersLine = /const TIERS = await Promise\.all\(\[([\d\s,]+)\]\.map\(\(t\) => safeImport\(`\.\/kits\/tier\$\{t\}\.js`\)\)\);/;
  const tiers = tiersLine.exec(src);
  const tierIds = tiers ? tiers[1].split(',').map((s) => Number(s.trim())).filter((n) => Number.isInteger(n)) : [];
  // `import('./x.js')` must appear at the call site itself: a bundler resolves a *literal* specifier, but it
  // cannot see through safeImport(path). safeImport gets the already-created promise as its second argument,
  // so the guarded try/catch semantics of the original stay identical.
  const call = (spec) => `safeImport('${spec}', import('${spec}'))`;
  let patched = src.replace(domainsLine, `const DOMAINS = await Promise.all([${domainNames.map((n) => call(`./${n}.js`)).join(', ')}]);`);
  if (tiers) patched = patched.replace(tiersLine, `const TIERS = await Promise.all([${tierIds.map((t) => call(`./kits/tier${t}.js`)).join(', ')}]);`);
  writeFileSync(file, patched);
  const tierNote = tierIds.length ? `${tierIds.length} tiers + ` : '';
  log(`.generated/: content modules ${tierNote}${domainNames.length} domains (${domainNames.join(', ')})`);
}

/**
 * The kit registry (server/sim/content/kits/index.js, 0.2.x): one file per operator kit, each loaded with a
 * guarded dynamic import from its own list. The lists are literal string arrays in the source, so they are read
 * back out and the three loading expressions are replaced by literal call lists (see §3 note 1).
 */
function patchKitsIndex(file) {
  if (!existsSync(file)) {
    log('.generated/: no content/kits/index.js (an older layout) — kit files need no rewrite');
    return;
  }
  const src = readFileSync(file, 'utf8');
  const helperLine = /async function (\w+)\((file)\) \{\r?\n(\s+)try \{\r?\n(\s+)return await import\(`\.\/ops\/\$\{file\}`\);/;
  const helper = helperLine.exec(src);
  if (!helper && !/import\(`\.\/ops\//.test(src)) {
    log('.generated/: kit files already use literal loaders — no rewrite needed');
    return;
  }
  if (!helper) {
    throw new Error('server/sim/content/kits/index.js no longer matches the expected kit-loader shape — '
      + 'cloudflare/build.mjs needs the literal rewrite updated (see build.mjs §3)');
  }
  const [, helperName, argName] = helper;
  /** Read `export const NAME = Object.freeze([...])` and return its string arrays (nested or flat). */
  const listOf = (name) => {
    const head = `export const ${name} = Object.freeze([`;
    const start = src.indexOf(head);
    if (start < 0) throw new Error(`kits/index.js: could not find ${name}`);
    // balanced scan: the first `]` of a *comment* must not end the array
    let depth = 0;
    let end = -1;
    for (let j = start + head.length - 1; j < src.length; j++) {
      if (src[j] === '[') depth++;
      else if (src[j] === ']') { depth--; if (depth === 0) { end = j; break; } }
    }
    if (end < 0) throw new Error(`kits/index.js: ${name} is not closed`);
    // comments may sit between the entries (they mention other file names) — drop them before reading strings
    const body = src.slice(start + head.length, end).replace(/\/\/[^\n]*/g, '').replace(/\/\*[\s\S]*?\*\//g, '');
    const groups = [];
    let cur = null;
    for (const tok of body.matchAll(/'([^']+)'|\[|\]/g)) {
      if (tok[0] === '[') { cur = []; groups.push(cur); }
      else if (tok[0] === ']') { cur = null; }
      else if (cur) cur.push(tok[1]);
      else groups.push([tok[1]]); // a flat list: every entry stands alone
    }
    if (!groups.length) throw new Error(`kits/index.js: ${name} has no files`);
    return groups;
  };
  const literal = (spec) => `${helperName}('${spec}', import('./ops/${spec}'))`;
  const flat = (arr) => `[${arr.map(literal).join(', ')}]`;
  // each group needs its own Promise.all: `Promise.all([[...], [...]])` would hand back the inner arrays
  // with their promises still pending, and every tier kit would silently merge to nothing
  const nested = (groups) => `[${groups.map((g) => `Promise.all(${flat(g)})`).join(', ')}]`;
  const kitFiles = listOf('KIT_FILES');
  const standinFiles = listOf('STANDIN_KIT_FILES').flat();
  const operatorFiles = listOf('OPERATOR_KIT_FILES').flat();
  // every listed file must exist (a renamed/removed kit file fails the build here, not at runtime)
  const opsDir = join(dirname(file), 'ops');
  const onDisk = new Set(readdirSync(opsDir).filter((f) => f.toLowerCase().endsWith('.js')));
  const missing = [...kitFiles.flat(), ...standinFiles, ...operatorFiles].filter((f) => !onDisk.has(f));
  if (missing.length) throw new Error(`kits/index.js lists files that are not in kits/ops/: ${missing.join(', ')}`);

  let patched = src
    .replace(helperLine, `async function ${helperName}(${argName}, loading) {\n${helper[3]}try {\n${helper[4]}return await (loading || import(${argName}));`)
    .replace(/const MODULES = await Promise\.all\(KIT_FILES\.map\(\(group\) => Promise\.all\(group\.map\(\w+\)\)\)\);/, `const MODULES = await Promise.all(${nested(kitFiles)});`)
    .replace(new RegExp(`const STANDIN_MODULES = await Promise\\.all\\(STANDIN_KIT_FILES\\.map\\(\\${helperName}\\)\\);`), `const STANDIN_MODULES = await Promise.all(${flat(standinFiles)});`)
    .replace(new RegExp(`const OPERATOR_MODULES = await Promise\\.all\\(OPERATOR_KIT_FILES\\.map\\(\\${helperName}\\)\\);`), `const OPERATOR_MODULES = await Promise.all(${flat(operatorFiles)});`);
  if (patched.includes('KIT_FILES.map(') || patched.includes('OPERATOR_KIT_FILES.map(') || patched.includes('STANDIN_KIT_FILES.map(')) {
    throw new Error('kits/index.js: a computed kit-loading expression survived the rewrite');
  }
  writeFileSync(file, patched);
  const total = kitFiles.flat().length + standinFiles.length + operatorFiles.length;
  log(`.generated/: kit registry — ${total} kit files (${kitFiles.flat().length} tier, ${standinFiles.length} stand-in, ${operatorFiles.length} 自选) made literal`);
}

/**
 * The generic pass (see §3 notes 2 and 3): guarded-import helpers in every file of the copied tree.
 * @param {string} root
 * @returns {number} how many call sites were rewritten
 */
function adaptGeneratedTree(root) {
  let helperSites = 0;
  let callSites = 0;
  for (const file of walkJs(root)) {
    let src = readFileSync(file, 'utf8');
    const before = src;

    // 2a. the helper itself: `async function NAME(path) { try { return await import(path);`
    const helperRe = /async function (\w+)\(path\) \{\r?\n(\s+)try \{\r?\n(\s+)return await import\(path\);/g;
    const helpers = new Set();
    src = src.replace(helperRe, (m, name, i1, i2) => {
      helpers.add(name);
      helperSites++;
      return `async function ${name}(path, loading) {\n${i1}try {\n${i2}return await (loading || import(path));`;
    });

    // 2b. literal call sites of those helpers: NAME('./x.js') → NAME('./x.js', import('./x.js'))
    for (const name of helpers) {
      const callRe = new RegExp(`\\b${name}\\(\\s*'(\\./[^']+\\.js)'\\s*\\)`, 'g');
      src = src.replace(callRe, (m, spec) => {
        callSites++;
        return `${name}('${spec}', import('${spec}'))`;
      });
    }

    if (src !== before) {
      writeFileSync(file, `// Adapted by cloudflare/build.mjs (guarded dynamic imports made bundler-resolvable; see build.mjs §3).\n${src}`);
    }
  }

  // 3. nothing may be left that the bundler cannot resolve
  const leftovers = [];
  for (const file of walkJs(root)) {
    const src = readFileSync(file, 'utf8');
    const re = /\bimport\(\s*`[^`]*\$\{/g;
    for (const m of src.matchAll(re)) leftovers.push(`${relative(repo, file)}: ${src.slice(m.index, m.index + 60).split('\n')[0]}`);
  }
  if (leftovers.length) {
    throw new Error(`computed dynamic import(s) the bundler cannot resolve:\n  ${leftovers.join('\n  ')}\n`
      + 'Add them to the adaptation in cloudflare/build.mjs §3.');
  }
  const files = walkJs(root).length;
  log(`.generated/: ${files} modules adapted (${helperSites} guarded-import helpers, ${callSites} call sites made literal)`);
  return callSites;
}

/** @param {string} dir @returns {string[]} every .js file below dir */
function walkJs(dir, out = []) {
  for (const d of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, d.name);
    if (d.isDirectory()) walkJs(abs, out);
    else if (d.isFile() && d.name.toLowerCase().endsWith('.js')) out.push(abs);
  }
  return out;
}

// ------------------------------------------------------------------------------------------------
// 4. Generated modules
// ------------------------------------------------------------------------------------------------

// Content packs (0.2.x): the registry is a file-system scan (server/packs.js), so it is resolved here, at build
// time, and baked into the Worker — the index body for GET /packs/index.json and the list of files a pack's
// manifest actually names, which is the only thing GET /packs/<id>/<file> may serve.
{
  const { scanPacks, packIndexOf } = await import(pathToFileURL(join(repo, 'server', 'packs.js')).href);
  const scan = scanPacks({ publicDir: join(repo, 'public'), dataDir: join(repo, 'data'), packsDir });
  const index = packIndexOf(scan.packs);
  const servable = [];
  for (const pack of scan.packs) {
    if (!pack.supported || pack.layout !== 'folder') continue; // language packs are plain files (/i18n/…, /data/i18n/…)
    for (const f of Object.values(pack.files)) servable.push(`${pack.id}/${f.rel}`);
  }
  writeFileSync(join(here, 'src', 'packs.generated.js'), [
    '// Generated by cloudflare/build.mjs — do not edit.',
    '// The content-pack registry of the deployment (server/packs.js scans the file system; a Worker cannot).',
    '// PACK_INDEX is what GET /packs/index.json returns; PACK_SERVABLE lists the <packId>/<rel> files a manifest',
    '// names — the only paths GET /packs/<id>/<file> may serve (src/worker.js).',
    `export const PACK_INDEX = ${JSON.stringify(index)};`,
    `export const PACK_SERVABLE = new Set(${JSON.stringify(servable)});`,
    '',
  ].join('\n'));
  const langs = scan.packs.filter((p) => p.type === 'lang').map((p) => p.manifest.lang ?? p.id);
  log(`packs: ${scan.packs.length} loaded${langs.length ? ` (languages: ${langs.join(', ')})` : ''}, `
    + `${servable.length} servable file(s)${scan.skipped.length ? `, ${scan.skipped.length} skipped` : ''}`);
  for (const s of scan.skipped.slice(0, 5)) log(`       skipped ${s.where}: ${s.problems.join('; ')}`);
}

// A fork's own announcement config (config/announcements.json — the file xinhai-ai's server reads) is baked in as
// the default document, so editing that file and redeploying keeps working. KV (when bound) and the
// SP_ANNOUNCEMENTS var take precedence; neither upstream has this file, so this is a no-op for the original.
{
  const cfg = join(repo, 'config', 'announcements.json');
  let doc = null;
  if (existsSync(cfg)) {
    try { doc = JSON.parse(readFileSync(cfg, 'utf8')); } catch (e) { throw new Error(`config/announcements.json is not valid JSON: ${e.message}`); }
    log(`config/announcements.json: ${Array.isArray(doc && doc.announcements) ? doc.announcements.length : 0} entr(ies) bundled as the default announcement document`);
  }
  writeFileSync(join(here, 'src', 'announce-config.generated.js'), [
    '// Generated by cloudflare/build.mjs — do not edit.',
    '// The repo config/announcements.json (a fork feature), used when neither the KV binding nor the',
    '// SP_ANNOUNCEMENTS var provides a document; null on a checkout without that file.',
    `export const DEFAULT_ANNOUNCEMENTS = ${doc ? JSON.stringify(doc) : 'null'};`,
    '',
  ].join(String.fromCharCode(10)));
}

// This deployment's own 「关于本服务器」 document (config/server-info.json, same KV story as the announcements).
{
  const cfg = join(here, 'config', 'server-info.json');
  let doc = null;
  if (existsSync(cfg)) {
    try { doc = JSON.parse(readFileSync(cfg, 'utf8')); } catch (e) { throw new Error(`config/server-info.json is not valid JSON: ${e.message}`); }
    log(`config/server-info.json: ${Array.isArray(doc && doc.rows) ? doc.rows.length : 0} row(s) baked in as the default 关于本服务器 content`);
  }
  writeFileSync(join(here, 'src', 'server-info-config.generated.js'), [
    '// Generated by cloudflare/build.mjs — do not edit.',
    '// The deployment config/server-info.json (edit cloudflare/config/server-info.json), used when neither the KV',
    '// binding nor the SP_SERVER_INFO var provides a document; null keeps the checkout content.',
    `export const DEFAULT_SERVER_INFO = ${doc ? JSON.stringify(doc) : 'null'};`,
    '',
  ].join(String.fromCharCode(10)));
}

const dataFiles = readdirSync(join(repo, 'data')).filter((f) => f.toLowerCase().endsWith('.json')).sort();
const imports = [];
const entries = [];
dataFiles.forEach((file, i) => {
  const id = `d${i}`;
  imports.push(`import ${id} from '../../data/${file}';`);
  entries.push(`  '${file}': ${id},`);
});
writeFileSync(join(here, 'src', 'data-modules.generated.js'), [
  '// Generated by cloudflare/build.mjs — do not edit.',
  '// Every data/*.json under the repository root, imported as text (the Text rule in wrangler.jsonc);',
  '// src/data-boot.js writes them into the Workers VFS and hands the directory to server/data.js.',
  ...imports,
  '',
  'export const DATA_TEXT = {',
  ...entries,
  '};',
  '',
].join('\n'));

const tag = computeBuildTag(repo);
writeFileSync(join(here, 'src', 'build-info.generated.js'), [
  '// Generated by cloudflare/build.mjs — do not edit.',
  '// The tag /healthz reports (server/index.js buildTag): a page whose own build is older reloads itself',
  '// (public/js/ui/buildGuard.js). Baked in at build time: a Worker cannot stat the served runtime.',
  `export const BUILD_TAG = ${JSON.stringify(tag)};`,
  `export const BUILT_AT = ${JSON.stringify(new Date().toISOString())};`,
  '',
].join('\n'));

// ------------------------------------------------------------------------------------------------
// 5. Report
// ------------------------------------------------------------------------------------------------

const { count, bytes, largest, oversize } = scan(dist);
log(`dist: ${count} files, ${(bytes / 1024 / 1024).toFixed(1)} MiB (largest ${largest.file} ${(largest.bytes / 1024 / 1024).toFixed(1)} MiB)`);
log(`data/*.json bundled into the Worker: ${dataFiles.length} files`);
log(`build tag: ${tag}`);
if (oversize.length) log(`WARNING: ${oversize.length} files exceed the 25 MiB per-file limit: ${oversize.slice(0, 3).map((f) => f.file).join(', ')}`);
if (!existsSync(join(repo, 'public', 'assets'))) {
  log('WARNING: public/assets is missing — run `node tools/setup.mjs` in the repository root to download the game assets');
  log('         (without them the game runs with placeholder art; see docs/DEPLOY.md §5)');
}
if (!existsSync(join(repo, 'public', 'fonts'))) log('WARNING: public/fonts is missing — run `node tools/setup.mjs`');
if (count > MAX_FILES_FREE) {
  const plan = count > MAX_FILES_PAID ? 'exceeds even the paid limit' : 'needs a paid plan (Workers Paid: 100,000 files)';
  log(`NOTE: ${count} files > ${MAX_FILES_FREE} (free-plan limit): this deploy ${plan}`);
}
const localGroups = localArtGroups ? JSON.parse(readFileSync(localArt, 'utf8')).count : 0;
log(localGroups ? `local art manifest: ${localGroups} entries` : 'local art manifest: empty stand-in written (no public/assets/local)');
log('done. next: npx wrangler dev   (or npx wrangler deploy)');

// ------------------------------------------------------------------------------------------------
// helpers
// ------------------------------------------------------------------------------------------------

/** server/sim → dist/sim, `.js` only, nodeData.js excluded (SIM_PRIVATE). */
function copySim(from, to) {
  mkdirSync(to, { recursive: true });
  for (const d of readdirSync(from, { withFileTypes: true })) {
    const src = join(from, d.name);
    const dst = join(to, d.name);
    if (d.isDirectory()) { copySim(src, dst); continue; }
    if (!d.isFile()) continue;
    if (SIM_PRIVATE.has(d.name.toLowerCase())) continue;
    cpSync(src, dst);
  }
}

/** server/index.js computeBuildTag: sha1 over "path\0size\0mtime" of every file under BUILD_INPUTS. */
function computeBuildTag(root) {
  const out = [];
  for (const rel of BUILD_INPUTS) collect(join(root, rel), rel, out);
  if (!out.length) return null;
  out.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  const h = createHash('sha1');
  for (const [rel, size, mtime] of out) h.update(`${rel}\0${size}\0${Math.floor(mtime)}\n`);
  return h.digest('hex').slice(0, 12);
}

function collect(abs, rel, out) {
  let st;
  try { st = statSync(abs); } catch { return; }
  if (st.isDirectory()) {
    for (const name of readdirSync(abs)) collect(join(abs, name), `${rel}/${name}`, out);
    return;
  }
  if (st.isFile()) out.push([rel.replace(/\\/g, '/'), st.size, st.mtimeMs]);
}

function scan(root, acc = { count: 0, bytes: 0, largest: { file: '', bytes: 0 }, oversize: [] }) {
  for (const d of readdirSync(root, { withFileTypes: true })) {
    const abs = join(root, d.name);
    if (d.isDirectory()) { scan(abs, acc); continue; }
    const st = statSync(abs);
    acc.count++;
    acc.bytes += st.size;
    const rel = relative(root, abs);
    if (st.size > acc.largest.bytes) acc.largest = { file: rel, bytes: st.size };
    if (st.size > MAX_FILE_BYTES) acc.oversize.push({ file: rel, bytes: st.size });
  }
  return acc;
}
